name: CI
on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend-deploy-staging:
    # needs:
    #   - backend-tests
    #   - frontend-tests
    # if: |
    #   github.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for backend changes
        run: |
          echo "BACKEND_HAS_CHANGED=true" >> "$GITHUB_ENV"

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy to staging
        if: env.BACKEND_HAS_CHANGED == 'true'
        # if: github.ref_name == 'main'
        run: |
          echo '${{ github.ref_name }}'
        # uses: akhileshns/heroku-deploy@v3.14.15
        # with:
        #   heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        #   heroku_app_name: ${{secrets.HEROKU_APP_NAME_STAGING}}
        #   heroku_email: ${{secrets.HEROKU_EMAIL}}

      - name: Don't deploy to staging
        if: env.BACKEND_HAS_CHANGED == 'false'
        run: |
          echo "No change detected in backend/. The app will not be deployed."

