name: CI
on:
  push:
    branches: [main]
  release:
    types: [released]
  pull_request:

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check for changes in foo
        run: |
          # Get the last commit before this one on main
          PREVIOUS=$(git rev-parse HEAD^)
          CURRENT=$(git rev-parse HEAD)

          echo "Checking for changes between $PREVIOUS and $CURRENT:"

          if git diff --name-only $PREVIOUS $CURRENT | grep '^foo'; then
            echo "FOO_HAS_CHANGED=true" >> "$GITHUB_ENV"
          else
            echo "FOO_HAS_CHANGED=false" >>  "$GITHUB_ENV"
          fi

          echo '${{ github.event.action  }}'
  deploy:
    needs:
      - foo
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'released' }}
    steps:
      - name: Pull repository
        uses: actions/checkout@v4
